### ISSUE TITLE
Is Human Readable midi data support

### ISSUE THREAD

**Issue by elmcapp** [chris-zen/coremidi#37]
Looks like this is the raw midi data. Is there any way to convert it to friendly humans readable midi data

**Comment by chris-zen** [comment]
Hi @elmcapp, this library is a wrapper around CoreMIDI, which doesn't provide a higher level view of the MIDI messages, but only raw bytes/words. If you need something more high level, you can use some of these libraries on top of this one:

- [rimd](https://github.com/RustAudio/rimd)
- [midi-rs](https://github.com/samdoshi/midi-rs)
