### ISSUE TITLE
MIDIClientDispose causes trouble on iOS

### ISSUE THREAD

**Issue by deermichel** [chris-zen/coremidi#39]
Hey there! I'm using your library in my iOS app and came across one of those pesky CoreMIDI bugs. I traced it down to the [`MIDIClientDispose`](https://github.com/chris-zen/coremidi/blob/master/src/client.rs#L335) call in the Drop implementation for Client.

## What is happening
I have a document-based app and every document has a MIDI client attached, i.e. when opening a doc, a MIDI client gets created (`MIDIClientCreate`) and when closing the doc, it gets destroyed (`MIDIClientDispose`). This works fine as long as the app is used in the foreground. However, when I put the app to background after closing a doc - then bringing it to the front and opening a doc, all subsequent calls of `MIDIClientCreate` fail with OSStatus -50.

Digging a little into it, -50 will be returned either for invalid arguments (checked them, all good) or issues with the MIDI server ([src](https://stackoverflow.com/a/30918853/1993349)). Finally, I came across this discussion note for the dispose call in the [Apple docs](https://developer.apple.com/documentation/coremidi/1495335-midiclientdispose?language=objc):
> Don’t explicitly dispose of your client; the system automatically disposes all clients when an app terminates. However, if you call this method to dispose the last or only client owned by an app, the MIDI server may exit if there are no other clients remaining in the system. If this occurs, all subsequent calls by your app to [MIDIClientCreate](https://developer.apple.com/documentation/coremidi/1495360-midiclientcreate?language=objc) and [MIDIClientCreateWithBlock](https://developer.apple.com/documentation/coremidi/1495330-midiclientcreatewithblock?language=objc) fail.

My hypothesis is, as all clients are disposed when backgrounding the app, iOS decides to kill the MIDI server and doesn't restart it when bringing the app back to the foreground. This might be categorized as an iOS bug, but on the other hand, Apple explicitly discourages the use of `MIDIClientDispose`. Once the MIDI server is killed by the OS, there is no chance to recover unless doing a full app restart.

## Suggestion
Remove the `Drop` implementation from Client as cleanup is handled by the system.

## Workaround
As long as one MIDI client is around, the MIDI server stays alive. Therefore calling `MIDIClientCreate` somewhere during app init and omitting the dispose call does the trick.

**Comment by chris-zen** [comment]
Hi @deermichel, thank you very much for the detailed report.

I think your suggestion makes sense, as I have seen people having trouble with this before.

I don't promise you a fast fix, but I will do it eventually. I'll keep this open until I can work on it.

Thanks!

**Comment by chris-zen** [comment]
Sorry @deermichel , better late than never :-P

**Comment by deermichel** [comment]
@chris-zen haha good one, thanks, appreciate it 😅 - i eventually ditched the Core* stuff and moved on to greener pastures
