### ISSUE TITLE
Report a vulnerability in chris-zen/coremidi

### ISSUE THREAD

**Issue by snowroll** [chris-zen/coremidi#42]
Hello, we have found a vulnerability in this repository, which may present serious security risks. However, we have been unable to locate a contact email to report the details of this vulnerability. We would like to know if you can provide an email address to confidentially discuss this matter and avoid public disclosure.

**Comment by chris-zen** [comment]
I'm sorry to sound suspicious, but I cannot give any personal information to someone who has not identified themselves appropriately. Perhaps you want to contribute an MR with the fix?

I'll be closing this issue unless you provide more details.

**Comment by snowroll** [comment]
I have submitted a pull request #45 and included the details of the vulnerability in the description.
